---
ansible_connection: winrm
ansible_winrm_scheme: http
ansible_winrm_transport: ntlm
ansible_winrm_port: 5985
ansible_winrm_server_cert_validation: ignore
ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
become: true
