- name: sowftware installation
  #win_package:
  ansible.windows.win_package:
    path: '{{ dest_folder }}'
    arguments:
    - /quiet
    - installdir="d:\temp\jenkins"
    - JAVA_HOME="c:\dev\java\openjdk11"
  register: adx

#- debug: msg="{{ adx.stdout }}"

#- debug: msg="{{ adx.stderr }}"
