- name: sowftware installation
  #win_package:
  ansible.windows.win_package:
    path: '{{ dest_folder }}'
    register: adx
    arguments:
    - /q

- debug: msg="{{ adx.stdout }}"

- debug: msg="{{ adx.stderr }}"
