---
- name: Executables files copy
  tasks:
    - name:
      ansible.windows.win_copy:
      src: '{{ source_folder }}'
      dest: '{{ dest_folder }}'
      remote_src: yes
      register: grep_ok

    - name: Print stdout
      debug:
        msg: "{{ grep_ok.stdout }}"
#       msg: "{{ grep_ok.results | map(attribute='stdout') | list }}"